import numpy as np

clip_i_scores_all=[]
clip_t_scores_all=[]
dino_scores_all=[]
for i in range(1,7):
    data1=np.load(f'clip_i_scores_rhr_gp{i}.npy')
    data2=np.load(f'clip_t_scores_rhr_gp{i}.npy')
    data3=np.load(f'dino_scores_rhr_gp{i}.npy')
    data4=np.load(f'clip_scores_direct_infer_gp{i}.npy')
    data5=np.load(f'clip_t_scores_direct_infer_gp{i}.npy')
    data6=np.load(f'dino_scores_direct_infer_gp{i}.npy')
    clip_i_scores_all.append(data4)
    clip_t_scores_all.append(data5)
    dino_scores_all.append(data6)
    print(f'This is the result of group {i}')
    # print(f'data1.shape {data1.shape}')
    # print(f'data2.shape {data2.shape}')
    # print(f'data3.shape {data3.shape}')
    # print(f'data4.shape {data4.shape}')
    # print(f'data5.shape {data5.shape}')
    # print(f'data6.shape {data6.shape}')
    print(f'data1.mean {data1.mean()}')
    print(f'data2.mean {data2.mean()}')
    print(f'data3.mean {data3.mean()}')
    print(f'data4.mean {data4.mean()}')
    print(f'data5.mean {data5.mean()}')
    print(f'data6.mean {data6.mean()}')
    print('-'*30)
clip_i_scores_all=np.array(clip_i_scores_all)
clip_i_scores_all=clip_i_scores_all.reshape(-1)
clip_t_scores_all=np.array(clip_t_scores_all)
clip_t_scores_all=clip_t_scores_all.reshape(-1)
dino_scores_all=np.array(dino_scores_all)
dino_scores_all=dino_scores_all.reshape(-1)
print(f'clip_i_scores_all.mean {clip_i_scores_all.mean()}')
print(f'clip_i_scores_all.shape {clip_i_scores_all.shape}')
print(f'clip_t_scores_all.mean {clip_t_scores_all.mean()}')
print(f'clip_t_scores_all.shape {clip_t_scores_all.shape}')
print(f'dino_scores_all.mean {dino_scores_all.mean()}')
print(f'dino_scores_all.shape {dino_scores_all.shape}')